
lang: en

#theme: jekyll-theme-cayman
remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

scss: |
  .header{background:#e67e22}
  .sidebar{background:#e67e22}
  .toctree{.caption{color:#0f1010}}
  :root {
    @for $level from 1 through 12 {
      @if $level % 4 == 0 {
        --toc-#{$level}: #{darken($theme-orange, 4 * 8.8%)};
      } @else {
        --toc-#{$level}: #{darken($theme-orange, $level % 4 * 8.8%)};
      }
    }
  }

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions