
lang: en

#theme: jekyll-theme-cayman
remote_theme: rundocs/jekyll-rtd-theme

scss: |
  .wy-nav-content-wrap{background:#a45e24}

readme_index: with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions