
lang: en

#theme: jekyll-theme-cayman
remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

scss: |
  .header{background:#e67e22}
  .sidebar{background:#e67e22}
  .toctree{.caption{color:#0f1010}}


plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

incremental: true
profile: true
